#conda env create -f environment.yml
#conda env update -f environment.yml --prune
name: hrh
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - pandas
  - matplotlib
  - numpy
  - pip
  - pip:
    - pyshp